app: agent1.c array_reverse_stack1.c array_list1.c array_2d.c array_1d.c array_queue.c quick_arg_sort.c
	gcc -std=c99 -o app agent1.c array_reverse_stack1.c array_list1.c array_2d.c array_1d.c array_queue.c quick_arg_sort.c
